module.exports = {
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    INVALID_STATUS: 'INVALID_STATUS',
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    PAYMENT_EXCEEDS_DUE: 'PAYMENT_EXCEEDS_DUE',
    GL_ACCOUNT_MISSING: 'GL_ACCOUNT_MISSING',
};
